server:
  port: 8082 # 微服务端口号

bocchi:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xieVictory
    admin-ttl: 3600000 # 访问令牌1小时
    admin-token-name: token
    # 管理员刷新令牌
    admin-refresh-secret-key: refreshAdminKey
    admin-refresh-ttl: 259200000 # 72小时
    admin-refresh-token-name: refresh_token
    user-secret-key: xieVictory
    user-ttl: 3600000 # 访问令牌1小时
    user-token-name: authentication
    # 用户刷新令牌
    user-refresh-secret-key: refreshUserKey
    user-refresh-ttl: 259200000 # 72小时
    user-refresh-token-name: refresh_authentication
  db:
    host: localhost
    port: 3306
    database: product-service
  redis:
    host: 192.168.182.100
    port: 6379